spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201
 
spring:
  profiles: dev
  application:
      name: microconfig-test-client111
  cloud:
    stream:
      kafka:
        binder:
          brokers: 47.93.184.137

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7301/eureka    #将7001改成了7301
    
info:
  app.name: microservice-config-client-dev-update11
  company.name: yc111
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7001/eureka
